pipeline {
    agent any
    environment {
        AWS_REGION = 'ap-northeast-2'
        ECR_REPO_NAME = 'eatbook-be-app-ecr'
        AWS_ACCOUNT_ID = '992382409749'
        IMAGE_TAG = "latest"
        ECR_REPO_URI = "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO_NAME}"
        COMPOSE_FILE = 'docker-compose.yml'
    }
    stages {
        stage('Checkout Code') {
            steps {
                dir('backend') {
                    git url: 'https://github.com/ktb-eatbook/eatbook-app-backend.git', branch: 'feat/ci-cd', credentialsId: 'github-access-token-id'
                }
                dir('infra') {
                    git url: 'https://github.com/ktb-eatbook/eatbook-infra.git', branch: 'main', credentialsId: 'github-access-token-id'
                }
            }
        }
        stage('Move Config Files') {
            steps {
                script {
                    sh '''
                    cp infra/docker/app-backend/Dockerfile backend/
                    cp infra/docker/app-backend/docker-compose.yml backend/
                    cp -r infra/config/* backend/src/main/resources/
                    sudo chown jenkins:jenkins backend/src/main/resources/.env
                    sudo chmod 644 backend/src/main/resources/.env
                    '''
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                dir('backend') {
                    script {
                        docker.build("${ECR_REPO_NAME}:${IMAGE_TAG}", ".")
                    }
                }
            }
        }
        stage('Deploy with Docker Compose') {
            steps {
                dir('backend') {
                    script {
                        sh '''
                        docker-compose -f ${COMPOSE_FILE} down || true
                        docker-compose -f ${COMPOSE_FILE} up --force-recreate -d
                        '''
                    }
                }
            }
        }
    }
}